// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reor.Software.PROJECT.Infrastructure.Persistence;

#nullable disable

namespace Reor.Software.PROJECT.Infrastructure.Migrations
{
    [DbContext(typeof(PROJECTDbContext))]
    [Migration("20260814152809_initial-example-greeting")]
    partial class initialexamplegreeting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Reor.Software.PROJECT.Infrastructure.Entities.GreetingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Greetee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Greeter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("greeting_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
